Update the poetry file and readme
Release-Engineering-Group-13/CS4295_FinalProject pull request #3
Opened 2024-05-03 12:09 UTC by nickdubbel

2024-05-03 14:37 UTC, Maartenvb02 requested changes

2024-05-03 14:37 UTC, Maartenvb02 commented on README.md
>      ```bash
Instead it is also possible to let Poetry create a virtual environment, it think that might be easier
```suggestion
2. Install Poetry
    ```bash
```

2024-05-03 14:37 UTC, Maartenvb02 commented on README.md
> +    source .venv/bin/activate
```suggestion
    curl -sSL https://install.python-poetry.org | python3 -
```

2024-05-03 14:37 UTC, Maartenvb02 commented on requirements.txt
We don't need requirements.txt anymore right?

2024-05-03 22:41 UTC, vtimmerTUD commented on requirements.txt
I don't think so? Although I wonder if we should leave it in just in case our peer reviewers didn't manage to get poetry to work.

2024-05-05 13:12 UTC, nickdubbel commented on requirements.txt
I think it would be nice to give a choice to the user.

2024-05-06 18:32 UTC, merged